Repository Azure/fleet-networking, pull requests merged in 2025-04, with the labels that each got.

#286 fix: bump go version to 1.23.6 for CVE
  .github/workflows/build-publish-mcr.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/go.yml
  .github/workflows/publish-image.yml
  .github/workflows/trivy.yml
  .github/workflows/unit-integration-tests.yml
  docker/hub-net-controller-manager.Dockerfile
  docker/mcs-controller-manager.Dockerfile
  docker/member-net-controller-manager.Dockerfile
  go.mod
Labels: Review effort 2/5

#275 docs: add a demo
  docs/demos/TrafficManagerProfile/README.md
  docs/demos/TrafficManagerProfile/session-build-multi-cluster-app/README.md
  docs/demos/TrafficManagerProfile/session-build-multi-cluster-app/build-multi-cluster-app.png
  docs/demos/TrafficManagerProfile/session-migrate-to-another-cluster/README.md
  docs/demos/TrafficManagerProfile/session-migrate-to-another-cluster/migrate-to-another-cluster.png
  docs/demos/TrafficManagerProfile/session-migrate-to-another-region/README.md
  docs/demos/TrafficManagerProfile/session-migrate-to-another-region/migrate-to-another-region.png
  docs/demos/TrafficManagerProfile/testfiles/crp.yaml
  docs/demos/TrafficManagerProfile/testfiles/deployment.yaml
  docs/demos/TrafficManagerProfile/testfiles/eastus2euap/nginx-service-eastus2euap.yaml
  docs/demos/TrafficManagerProfile/testfiles/eastus2euap/ro-nginx-service-eastus2euap.yaml
  docs/demos/TrafficManagerProfile/testfiles/eastus2euap/ro-nginx-service-export-eastus2euap.yaml
  docs/demos/TrafficManagerProfile/testfiles/nginx-backend-eastus2euap.yaml
  docs/demos/TrafficManagerProfile/testfiles/nginx-backend-uksouth.yaml
  docs/demos/TrafficManagerProfile/testfiles/nginx-profile.yaml
  docs/demos/TrafficManagerProfile/testfiles/placement-disruption-budget.yaml
  docs/demos/TrafficManagerProfile/testfiles/placement-eviction-member-1.yaml
  docs/demos/TrafficManagerProfile/testfiles/placement-eviction-member-3.yaml
  docs/demos/TrafficManagerProfile/testfiles/uksouth/nginx-service-uksouth.yaml
  docs/demos/TrafficManagerProfile/testfiles/uksouth/ro-nginx-service-export-uksouth.yaml
  docs/demos/TrafficManagerProfile/testfiles/uksouth/ro-nginx-service-uksouth.yaml
  docs/tutorials/ApplicationMigration/testfiles/ro-nginx-service-export.yaml
Labels: Review effort 3/5

#287 feat: populate resourceID for trafficManagerBackend
  pkg/controllers/hub/trafficmanagerbackend/controller.go
  pkg/controllers/hub/trafficmanagerbackend/controller_integration_test.go
  test/common/trafficmanager/azureprovider/profile.go
  test/common/trafficmanager/fakeprovider/endpoint.go
  test/common/trafficmanager/fakeprovider/profile.go
  test/common/trafficmanager/validator/backend.go
  test/e2e/traffic_manager_test.go
Labels: Review effort 3/5

#290 chore: fix the pipeline
  .github/workflows/publish-image.yml
  .github/workflows/trivy.yml
Labels: Review effort 1/5

#291 feat: add status metrics for trafficManagerBackend
  go.mod
  pkg/controllers/hub/trafficmanagerbackend/controller.go
  pkg/controllers/hub/trafficmanagerbackend/controller_integration_test.go
  pkg/controllers/hub/trafficmanagerprofile/controller.go
  pkg/controllers/hub/trafficmanagerprofile/controller_integration_test.go
Labels: Review effort 3/5

#292 feat: add validation for timeoutInSeconds for MonitorConfig in TrafficManagerProfile
  api/v1beta1/trafficmanagerprofile_types.go
  config/crd/bases/networking.fleet.azure.com_trafficmanagerprofiles.yaml
  pkg/controllers/hub/trafficmanagerprofile/controller_integration_test.go
  test/apis/v1beta1/api_validation_integration_test.go
Labels: Review effort 3/5

#294 chore: upgrade azidentity package to fix the CVE-2025-29923
  go.mod
  go.sum
Labels: Review effort 2/5

#296 feat: setup controller runtime logger
  cmd/hub-net-controller-manager/main.go
  cmd/mcs-controller-manager/main.go
  cmd/member-net-controller-manager/main.go
Labels: Review effort 2/5
