Repository Azure/fleet-networking, pull requests merged in 2025-05, with the labels that each got.

#295 chore: fix CVE-2025-22871
  .github/workflows/build-publish-mcr.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/go.yml
  .github/workflows/publish-image.yml
  .github/workflows/trivy.yml
  .github/workflows/unit-integration-tests.yml
  docker/hub-net-controller-manager.Dockerfile
  docker/mcs-controller-manager.Dockerfile
  docker/member-net-controller-manager.Dockerfile
  go.mod
Labels: Review effort 2/5

#293 docs: add atm troubleshooting doc
  docs/concepts/DNSBasedGlobalLoadBalancing/README.md
  docs/toubleshooting/DNSBasedGlobalLoadBalancing.md
Labels: Review effort 3/5

#297 docs: improve the traffic manager doc
  docs/concepts/DNSBasedGlobalLoadBalancing/README.md
  docs/toubleshooting/DNSBasedGlobalLoadBalancing.md
  docs/tutorials/ApplicationMigration/ApplicationMigration.md
  docs/tutorials/ApplicationMigration/after-migrate.png
  docs/tutorials/ApplicationMigration/before-migrate.png
  docs/tutorials/ApplicationMigration/during-migrate.png
  docs/tutorials/ApplicationMigration/testfiles/crp-availability.yaml
  docs/tutorials/ApplicationMigration/testfiles/envelop-object.yaml
  docs/tutorials/ApplicationMigration/testfiles/member-cluster-2.yaml
  docs/tutorials/ApplicationMigration/testfiles/nginx-backend.yaml
  docs/tutorials/ApplicationMigration/testfiles/nginx-profile.yaml
  docs/tutorials/ApplicationMigration/testfiles/nginx-service.yaml
  docs/tutorials/ApplicationMigration/testfiles/ro-nginx-service-export.yaml
  docs/tutorials/ApplicationMigration/testfiles/ro-nginx-service.yaml
  docs/tutorials/BuildMultiClusterApplication/BuildMultiClusterApplication.md
  docs/tutorials/BuildMultiClusterApplication/after.png
  docs/tutorials/BuildMultiClusterApplication/before.png
  docs/tutorials/BuildMultiClusterApplication/testfiles/crp-multi-cluster-app.yaml
  docs/tutorials/BuildMultiClusterApplication/testfiles/envelop-object.yaml
  docs/tutorials/BuildMultiClusterApplication/testfiles/member-cluster-2.yaml
  docs/tutorials/BuildMultiClusterApplication/testfiles/nginx-backend.yaml
  docs/tutorials/BuildMultiClusterApplication/testfiles/nginx-profile.yaml
  docs/tutorials/BuildMultiClusterApplication/testfiles/nginx-service.yaml
  docs/tutorials/BuildMultiClusterApplication/testfiles/ro-nginx-service.yaml
Labels: Review effort 3/5

#298 docs: fix the troubleshooting doc
  docs/toubleshooting/DNSBasedGlobalLoadBalancing.md
Labels: Review effort 1/5

#300 test: add the tests when public ip already exists in azure profile
  docs/demos/TrafficManagerProfile/session-migrate-to-another-cluster/README.md
  docs/demos/TrafficManagerProfile/session-migrate-to-another-region/README.md
  docs/toubleshooting/DNSBasedGlobalLoadBalancing.md
  test/e2e/traffic_manager_test.go
Labels: Review effort 3/5
